export const EXCEPTION = 'EXCEPTION';
export const CLEAR_EXCEPTION_MSG = 'CLEAR_EXCEPTION_MSG';

export const FETCH_MEDICINE_DETAIL_LOADING = 'FETCH_MEDICINE_DETAIL_LOADING';
export const FETCH_MEDICINE_DETAIL_LOADED = 'FETCH_MEDICINE_DETAIL_LOADED';
export const FETCH_MEDICINE_DETAIL_ERROR = 'FETCH_MEDICINE_DETAIL_ERROR';
export const SET_MEDICINE_DETAIL = 'SET_MEDICINE_DETAIL';


export const SET_PHONE_NUMBER = "SET_PHONE_NUMBER";

export const GRAPHCOOL_AUTH_TOKEN_OBTAINED = "GRAPHCOOL_AUTH_TOKEN_OBTAINED";
export const GRAPHCOOL_AUTH_TOKEN_ERROR = "GRAPHCOOL_AUTH_TOKEN_ERROR";
export const GRAPHCOOL_AUTH_TOKEN_CLEAR = "GRAPHCOOL_AUTH_TOKEN_CLEAR";

export const SET_USER_ID = "SET_USER_ID";
export const CLEAR_USER_ID = "CLEAR_USER_ID";

export const USER_DETAILS_LOADING = "USER_DETAILS_LOADING";
export const USER_DETAILS_LOADED = "USER_DETAILS_LOADED";
export const USER_DETAILS_ERROR = "USER_DETAILS_ERROR";
export const CLEAR_USER_DETAILS = "CLEAR_USER_DETAILS";