export const EXCEPTION = 'EXCEPTION';
export const CLEAR_EXCEPTION_MSG = 'CLEAR_EXCEPTION_MSG';

export const FETCH_MEDICINE_DETAIL_LOADING = 'FETCH_MEDICINE_DETAIL_LOADING';
export const FETCH_MEDICINE_DETAIL_LOADED = 'FETCH_MEDICINE_DETAIL_LOADED';
export const FETCH_MEDICINE_DETAIL_ERROR = 'FETCH_MEDICINE_DETAIL_ERROR';
export const SET_MEDICINE_DETAIL = 'SET_MEDICINE_DETAIL';